services:
  db:
    image: postgres:17.2-bookworm
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
  web:
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: